version: '3'

services:
  mysql:
    container_name: msg.prod.db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: msg.prod.redis
    command: /bin/sh -c "redis-server --requirepass msg"
    ports:
      - "6379:6379"


