
spring:
  profiles:
    active: ${PROFILE:local}
  web:
    resources:
      add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
        default_batch_fetch_size: 1000
        timezone:
          default_storage:
            NORMALIZE

  datasource:
    hikari:
      auto-commit: false
      connection-timeout: 2000
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true

  sql:
    init:
      mode: always

jwt:
  accessSecret: ${ACCESS_SECRET:qwertyuiopasdfghjklzxcvbnm12345678901234567890}
  refreshSecret: ${REFRESH_SECRET:poiuytrewqlkjhgfdsamnbvcxz12345678901234567890}
  accessExp: ${ACCESS_EXP:1800}
  refreshExp: ${REFRESH_EXP:7200}

gauth:
  clientId: 6844b9b18f2c40fbb48666e03fbbee0e0f252e8e281d4fa89295dd953f2b1c6f
  clientSecret: 93d55c5dc9a74cfeaebc31970619fad81369b48cba0c4d7faba40352ff1ac05b
  redirectUri: http://localhost:8080/auth

server:
  port: ${SERVER_PORT:8080}

