
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306}/${DB_NAME:hiv2}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}