name: HI_BACKEND_V2_CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.HI_MYSQL_PASSWORD }}
          MYSQL_DATABASE: hiv2
        ports:
          - 3306:3306
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 7
          redis-port: 6379
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '117'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application.yml
        run: |
          echo "${{ secrets.HI_BACKEND_ENV }}" > ./src/main/resources/application.yml
        shell: bash

      - name: Run build with Gradle wrapper
        run: ./gradlew clean build

      - name: Report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml

      - name: HIv2 Backend CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ HI-Backend-CI 성공! ✅
          webhook: ${{ secrets.HI_DISCORD_WEBHOOK }}
          color: 00FF00

      - name: HIv2 Backend CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗️ HI-Backend-CI 실패! ❗️
          webhook: ${{ secrets.HI_DISCORD_WEBHOOK }}
          color: FF0000